### ISSUE TITLE
Display & kb backlight keep going half brightness every reboot. 

### ISSUE THREAD

**Issue by nolen8** [seerge/g-helper#2987]
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hi! Everytime i restart my laptop, it gets extremely dim, at least half my usual brightness.
I tried downloading the visual modes and clicking "default" fixes the issue, but the second i reboot... it go back to dim again.

The keyboard backlight also keeps reverting to 50% brightness. This one i believe is being cause by the "silent" profile i am using, as the balanced profile dosent cause this issue. Is there a way to prevent this?

I dont know where to ask so ill ask here, is there a way to restore the UI elements from MyAsus when i mute/unmute my mic? (the microphone on/off box that pops up when you push it)

Thank you!!!

### How to reproduce the bug?

Reboot the laptop.

### Logs

[log.txt](https://github.com/user-attachments/files/16642610/log.txt)

### Device and Model

G16 GU603VV

### Additional information.

Fresh install of w11, fully updated. Have not installed ANY Asus software.

### Armoury Crate

Uninstalled

### Asus Services

6

### Version

GHelper v0.184

### OS

Windows 11 23H2

**Comment by nolen8** [comment]
Update: Just tested a few other visual modes and all work however, no matter which i select... the laptop resets it back to this dim profile on every boot. Something is resetting it back to default on startup but i dont see anything in the settings of neither ghelper nor windows.

**Comment by seerge** [comment]
@nolen8 hello,

G-Helper is not controlling brightness on your laptop, it's controlled by windows and GPU drivers. Modes like `Silent` or `Balanced` do not change brightness and don't cause that.

Most likely you have some power saving setting in windows, like [adaptive brightness](https://support.microsoft.com/en-us/windows/content-adaptive-brightness-control-in-windows-292d1f7f-9e02-4b37-a9c8-dab3e1727e78#:~:text=Select%20the%20Start%20button%2C%20then,contrast%20will%20not%20be%20adjusted.) or something else. Probably due to a fresh windows install.

You can try to reset windows [power plan to see if it helps](https://github.com/seerge/g-helper/wiki/Troubleshooting#resetting-windows-power-plan-to-defaults) and also make sure to stop all Asus services from `Extra`

Thanks

**Comment by nolen8** [comment]
Hi! i think there was some miscommunication. The brightness is changing due to the color profile changing. I fixed the brightness on the stock default profile, but i need to know how to fix it changing my color profile every boot.

The profile changes back to default on every reboot. Uninstalling the asus system driver fixed it so i think its related to that. I messed with power saving settings and adaptive brightness dosent exist on this model. (or at least i dont have a setting for it)

The profile question was completely separate issue. The keyboard bl is affected by the "silent" profile, it changes the kb light to 30%. I was curious if this is baked into the bios or can there be anything to prevent this?

**Comment by seerge** [comment]
@nolen8 

- If under "Uninstalling the asus system driver" you mean Asus System Control Interface - just stop asus services from `Extra` and it same have similar effect.
- Backlight brightness is remembered separately per plugged in / on battery states of the laptop. So when you unplug it would set last used level

**Comment by nolen8** [comment]
Thats my fault but i guess the application dosent explain that fuction very well, i kept assuming "stop" just halts the system services until you reboot and they will start up again. I just tested it and it keeps them off permanently! To clairfy, does this hault ass asus services until i click "start" again? Thank you!!! this seemed to do it. is there any benefit to keeping the asus services running?

The keyboard baclight is 100% a "silent" mode problem. It retains 100% brightness on every profile besides silent, and it stick AFTER silent mode is on, but the second the backlight turn off (due to sleep or 30 sec timeout), the next time the backlight comes on, the "silent" profile puts it back to 30% again (and moves the dial in ghelper)

**Comment by nolen8** [comment]
EDIT: disabling the asus services did NOT fix the color profile issue. asus services report as 0 but it still reverts my color profile after every reboot... this has been so much more frustraiting than armory crate ;-;

**Comment by seerge** [comment]
@nolen8 it stops and disables them from running. It says that in [requirements](https://github.com/seerge/g-helper/wiki/Requirements#recommendations-optional). If you don't use MyASUS there is no benefit in having them running. 

If disabling does not fix it - it means something else is changing graphic settings on your device, not G-Helper. You can just stop G-Helper from startup to verify that.

As for backlight brightness it's not connected with modes anyhow. It could be that (again) asus services were interfering.

Thanks

**Comment by nolen8** [comment]
seems like disabling the asus services fixed the keyboard backlight!!! Well thats one thing fixed accidently! hah thanks!!!

let me try disabling both ghelper and asus services and reporting back, thanks for all the support!!!

can i get the UI element from muting my mic on ghelper, or is that only a myasus thing?

**Comment by seerge** [comment]
@nolen8 what is "UI element from muting my mic on ghelper" ? If you mean toast notification saying that mic is muted, then G-Helper shows it again if asus services are not running (as otherwise they would handle that and show their own notification)

**Comment by nolen8** [comment]
Yes! and yes youre correct! just tested it and it shows. i tested it prior to disabling the services so it didnt work. Sorry for being all over the place! i kinda feel bad haha

disabling both ghelper and services still resulted in a color profile swap. ill have to figure it out but at least i have all of ghelpers issues resolved! thank you so much!! Do you happen to know what i can do in terms of looking at why it would be changing? i already tried messing with my gpu driver settings and windows power setting. the color profile shows an "asus" profile could that be it?

**Comment by seerge** [comment]
@nolen8 i don't know, but if setting a new visual mode "fixes" it. It means it some strange Intel GPU optimization probably to save battery or so. I would look into their command center (or how it's called) to check.

Also to be sure check windows `Task Scheduler` app for any scheduler asus apps that is set to run on startup, and delete startup tasks there.

**Comment by nolen8** [comment]
Thats probably true, thanks again for all the help and support!!

i got everything sorted now besides the profile so ill figure that out. I just shot ya a few bucks on paypal it isnt much but at least something! Besides the hiccups which are mostly all my part, its been great!

**Comment by seerge** [comment]
@nolen8 ok, no problem.

If setting Visual Mode in G-Helper "solves" dimming issue in your case, you can just take a command itself (where G-Helper runs AsusSplendid.exe to set this modes) and set it to run on startup manually in Task Scheduler

```
C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_9b2f1b4e956514ee\ASUSOptimization\AsusSplendid.exe 11 0 50
```

The reason app doesn't do that on start for "Default" Visual Mode is cause it assumes that it's already like that, and doesn't interfere.

Thanks

**Comment by nolen8** [comment]
Hi! sorry i dont know how else to communicate as i dont see an email or discord etc. If this isnt an appropriate place to comminate please let me know! 

New issue, when I put the laptop to sleep, no matter what it always goes into hibernation mode on it's own after a while (30 mins or so?). 

What I tried:

I do not have ANY hibernation settings in Windows or my power plan config, I looked everywhere. 
the hibernation sleep setting in g-helper is set to 0, yet still hibernates. Does this rely on asus services?

I tried a few more things  for the display color profile issue and wanted to post about it just in case someone else runs into this.

What i tried:

disabling the igpu and only running on dgpu stops this behavior. I looked in task scheduler and disabled basically everything, same issue.

DDU the igpu drivers, same issue. Resetting back to default color modes in the Intel command center/arc did permanently change the brightness of the default profile, but still reverts on every boot. I really think it's a Intel problem.

Thank you again! the keyboard light and mic button have now been working flawless with yesterdays help!!!

**Comment by seerge** [comment]
@nolen8 hello, glad that you have figured hibernation out. It's indeed just a native windows behavior to hibernate device after it looses something like 10% of charge in sleep. G-Helper's 30 minutes is separate (and controllable via app)

For color issues, you can just set 
```
C:\Windows\system32\DriverStore\FileRepository\asussci2.inf_amd64_9b2f1b4e956514ee\ASUSOptimization\AsusSplendid.exe 11 0 50
``` to run on startup as I mentioned above

**Comment by nolen8** [comment]
FIXED THE PROBLEM!!!!

For anyone having these issues, try uninstalling intel arc control. Immediately fixed my issue.

i noticed it changed my display colors everytime the arc control icon popped in my hidden icon menu.

**Comment by seerge** [comment]
@nolen8 ah ... does just removing arc control from startup solve this as well?

**Comment by nolen8** [comment]
im honestly not sure, ill reinstall it and report back for ya!

i still have the intel command center installed, only removed arc.

**Comment by seerge** [comment]
@nolen8 ah .. i thought it's same. I don't have an intel device so was not aware that there are so many different apps together.

Just in case your iGPU is not ARC as far as i know (your device is older) so you don't need it anyway

**Comment by nolen8** [comment]
it dosent matter its not arc, its bundled in the official intel installer and works on all modern intel igpus. I think its considered an "arc" product

installing arc again as i type

**Comment by nolen8** [comment]
disabling "arc control" on startup resolved it!!!!

if you dl the intel igpu drivers from intel.com, it bundles in arc on 11th gen and newer cpus (per the spec requirements)

this isnt an issue if you use windows update to install igpu drivers. Maybe making a note/warning about the official intel download bundling arc and causing color issues might be useful! (for refrence, this installer: https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)

everything is now resolved and working as intended!!! thank you so much!!
