### ISSUE TITLE
Found a Workaround for Brightness Control Bug

### ISSUE THREAD

**Issue by MaxHornet** [seerge/g-helper#4127]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [x] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

Hey Serge , i  think i have found a way to fix that brightness controll issue when we switch the mode from eco to standard.....

Beside from turning on the option for : enable gpu on shutdown

### How to reproduce the bug?

Switch eco to standard mode , brightness gets stuck.

### Logs

its a workaround.

### Device and Model

ASUS TUF GAMING F15 FX507ZV4

### Additional information.

After turning on gpu from eco to standard.

So the workaround is:

1) open services
2) search for Nvdia Display Container LS
3) rightclick on it and choose restart service

Then the problem gets fixed no restart required!

Is there any possibility of automating this fix inside GHelper?
This will be beneficial if its implemented.

![Image](https://github.com/user-attachments/assets/1cf0f3ee-ca5f-4d39-89bc-1154cacd793c)

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.208

### OS

23H2

**Comment by seerge** [comment]
@MaxHornet hello, I know that :) But someone wrote that restarting service doesn't help. So it may be not an ultimate solution tho.

And mainly - from what I remember it does not fix another issue that (could be) triggered by booting when GPU is disabled. Is [GPU refusing to get disabled again if you have enabled it.](https://github.com/seerge/g-helper/discussions/1042).

Do you face that too ? Does restarting nvidia service help ?

**Comment by MaxHornet** [comment]
No mine works correctly no issue with that , just the brightness gets fixed, i always shut down my laptop with dGPU disabled, I mostly use igpu , when I wanted to game I enable the dGPU and then restart the services to fix the brightness, after gaming I turn off the dGPU and shut it down.

**Comment by seerge** [comment]
@MaxHornet hello, 

Try this build, I have added service restart after every time GPU enable command runs (which I believe an overkill). But that just for a test :)

Keep in mind that you will have to run app as admin, as otherwise it won't have enough permissions to restart a service.

[GHelper.zip](https://github.com/user-attachments/files/20445218/GHelper.zip)

**Comment by MaxHornet** [comment]
@seerge Thanks dev that was quick!

I will test it and upload a log for it.

**Comment by MaxHornet** [comment]
@seerge Hi, just tested the build , I wanna say it's working flawlessly !

I tested multiple times eco on and off restarting from cold eco to standard ,it just works!

Here is the logs : 

[log.txt](https://github.com/user-attachments/files/20445793/log.txt)

**Comment by MaxHornet** [comment]
As this is a test build can I use this build for regular daily usage ?

I think you are right ,this fix is actually overkill as it restarts the service every time switching from eco to standard. Will there be any harm or consequences of doing this ? 

Before when I was using armory crate, the brightness don't get stuck when switching from eco to standard : maybe armory crate does the same thing by restarting the Nvdia services?


Lastly I want to suggest:
Maybe implementing this fix as an optional feature if you ever think of implementing it officially, Which might help some people who are already facing this issue.


Thanks for Your Awesome Support, really appreciate it.

**Comment by seerge** [comment]
@MaxHornet yes, restarting NV service for all devices all the time is an overkill :) As in most of the cases it's not needed.

But I have added this as an option, that you can toggle via config.

So just add following line to `%appdata%\GHelper\config.json` (quit app before editing)
```
"nv_restart": 1,
```

And it will do the restart. 

This build should allow that (and I will include this option in next releases). Thanks

[GHelper.zip](https://github.com/user-attachments/files/20455420/GHelper.zip)

**Comment by kanishk85** [comment]
I am not able to control my brightness even after the latest build, manually restarting the nv container service also doesn't work
model: asus tuf a15 fa507nu

[log.txt](https://github.com/user-attachments/files/20643112/log.txt)

**Comment by seerge** [comment]
@kanishk85 you can check `Enable GPU on shutdown` under `Extra`, it usually helps to prevent that in most of the cases :) 

But if you want to use the feature discussed in this topic (and added to the app), you need to manually toggle it in config.  

So just add following line to `%appdata%\GHelper\config.json` (quit app before editing)

```
"nv_restart": 1,
```

**Comment by seerge** [comment]
@MaxHornet hey, I was recently digging a bit deeper into this topic (for this [guy](https://github.com/seerge/g-helper/issues/4086)) ~~and in general, and noticed that AC seem to manually disable NV Platform under device manager.~~

So I have went even further, I have added an option under `Extra`  to Stop NV Platform in Eco (and start it back in Standard). Next to that it would also stop all NVidia services in Eco (and again start them back in standard).

And I have noticed that my G14 in Eco mode seem to gain like an 1w less discharge rate in idle

Obviously app needs to run as admin for that. 

Can you check if this build https://github.com/seerge/g-helper/pull/4524 also solves your "brightness" problem and if it anyhow improves discharge for you too ?

**Comment by MaxHornet** [comment]
@seerge Hello dev 

Sorry for late response I was a little busy.
I will check it today.

**Comment by MaxHornet** [comment]
@seerge hello, i have tested the build , its working not the first time but only after the second time, means when i boot the laptop from cold it was initially set to eco then selecting standard mode does not immediately fix the brightness, i have to switch it back to eco and then again back to standard to fully make it work, thats why its only working after second time putting to standard.
(The nvdia restart service always works the first time)

I see this build does not have that nvdia service restart thing it only has that device disable-enable thing you have added recently. 

And for the idle battery drain , its like 2w less than previous. Sits at 6.8 watts idle , previously it sits at 8.9 watts.

This new method is working actually , and i see that my system processs reduces to like 180 ish , no nvdia process running when in eco, so thats why i guess battery saving has improved. Previously  nvdia container will be running in eco always.


Here is the logs : 

[log.txt](https://github.com/user-attachments/files/22216635/log.txt)

**Comment by kanishk85** [comment]
@seerge I simply downgraded my NVIDIA driver and the brightness issue never returned after that.

**Comment by seerge** [comment]
@MaxHornet ok , it's strange that it doesn't help with brightness in your case - since it starts NV Container service each time you enable GPU  as well :)

**Comment by MaxHornet** [comment]
> [@MaxHornet](https://github.com/MaxHornet) ok , it's strange that it doesn't help with brightness in your case - since it starts NV Container service each time you enable GPU as well :)

@seerge I think the Nv platform thing just starts the service when setting to standard mode , but doesn't take effect immediately. But only after putting again to eco then to standard works.

On your previous implementation you are actually explicitly restarting the service which makes it effect immediately rather than just starting the service.

Maybe starting the service or restarting has different effects?


Does yours laptop brightness works immediately after setting it to standard? (Without the explicit restart service only the Nv platform start thing)

**Comment by seerge** [comment]
@MaxHornet 

Restarting service is actually stopping it and starting again :) Nothing else. And it starts it here too. That's why i was surprised.

My laptop does not have any brightness issues at all, in any circumstances and it doesn't need any of this shenanigans.

Btw, I was wrong about AC stopping NV Platform. I just installed it and checked, it just shuts down GPU with a single ON/OFF command same as G-Helper. NV Platform and all it's services actually keep running.

**Comment by MaxHornet** [comment]
@seerge Well thats a dead end i suppose, Asus just likes to keep all the laptop models unique with different problems of their own.

I will just stick to the nv restart thing it works for me.

If you want to test any thing else for this model just mention it I will be available.

**Comment by seerge** [comment]
@MaxHornet i'm also surprised that NV services actually consume resources when GPU is off, which seem to be nvidia drivers/software fault.

**Comment by MaxHornet** [comment]
@seerge Hey dev I think i have found the problem, after further testing why brightness only works after restart of nv service. 

(Using the official build)
Scenario 1 : (For Nv restart method)

The nvdia service always says running under services when in eco mode.
But changing from eco to standard fixes because of stopping the service and then starting it. (Here it first initiated a stop)


(Using the experimental build)
Scenario 2 : (For Nv Platform enable disable method)

When booting in eco the nvdia container in services is always saying running. When putting from eco to standard, the Nv platform starts all the nvdia services if it was in stop state. Here is the catch Nvdia Container was always running so nv platform did not started it from a stopped state so it didn't get effected and it kept on running. 

After that when I switch it back from standard to eco , Nv platform stops every nvdia services including Nvdia Container.
And again switching it from eco to standard nv platform starts all services ( This time Nvdia Container actually gets started from a stopped state), this is when the brightness control works.

Scenario 3 : (Setting nvdia container on manual mode rather than automatic)

So now when I cold boot in eco , the nvdia container was already in a stopped state.
After switching from eco to standard nv platform started every nvdia service(This time Nvdia Container started as this was already in stopped state). Now the brightness works immediately after that.

So in conclusion: 
Nvdia container requires to be started from a stopped state after booting. That's why restart service always worked. It first stops it then again starts it back.

Sorry for the length xd. I was just curious for finding the main cause.

**Comment by seerge** [comment]
@MaxHornet I have some updates

I have reconsidered stopping NV platform device, as it doesn't seem to solve any existing firmware / driver behavior issues.

But stopping and (re)starting nvidia services could be still an option.

I have simplified all changes I propose at https://github.com/seerge/g-helper/pull/4524 and left only service-specific action. Now it's pretty much same as you have asked with nv_restart, but with a checkbox under `Extra`. If not ticked - it does nothing new.

If ticked : it would STOP nvidia services when Eco mode is set, and RESTART nvidia services when Standard mode is set.
It doesn't disable services form running, so they will still run on reboot as usually.

It stops / starts 2 services
```
NVDisplay.ContainerLocalSystem
NvContainerLocalSystem
````

Can you check if this build works similar to nv_restart (in your case) ?

**Comment by MaxHornet** [comment]
Just tested the build , its working similarly.

I have noticed that it fixes one more thing the nvdia container logo sometimes stucks at eco mode under drop down hidden panel where we can switch display mode. Now it gets cleared in eco which is good. And reappears on standard.

Here are the logs: 

[log.txt](https://github.com/user-attachments/files/22415537/log.txt)

**Comment by seerge** [comment]
@MaxHornet ok, thanks for checking.

In your case, you seem to have only 1 service from 2 by some reason
```
9/19/2025 3:25:14 AM: powershell Restart-Service -Name 'NVDisplay.ContainerLocalSystem' -Force
9/19/2025 3:25:14 AM: 16623 ms: WARNING: Waiting for service 'NVIDIA Display Container LS (NVDisplay.ContainerLocalSystem)' to stop...
WARNING: Waiting for service 'NVIDIA Display Container LS (NVDisplay.ContainerLocalSystem)' to stop...
WARNING: Waiting for service 'NVIDIA Display Container LS (NVDisplay.ContainerLocalSystem)' to stop...
WARNING: Waiting for service 'NVIDIA Display Container LS (NVDisplay.ContainerLocalSystem)' to stop...
WARNING: Waiting for service 'NVIDIA Display Container LS (NVDisplay.ContainerLocalSystem)' to stop...
WARNING: Waiting for service 'NVIDIA Display Container LS (NVDisplay.ContainerLocalSystem)' to stop...
WARNING: Waiting for service 'NVIDIA Display Container LS (NVDisplay.ContainerLocalSystem)' to stop...

9/19/2025 3:25:14 AM: powershell Restart-Service -Name 'NvContainerLocalSystem' -Force
9/19/2025 3:25:14 AM: 303 ms: Restart-Service : Cannot find any service with service name 'NvContainerLocalSystem'.
At line:1 char:1
+ Restart-Service -Name 'NvContainerLocalSystem' -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (NvContainerLocalSystem:String) [Restart-Service], ServiceCommandExcepti 
   on
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.RestartServiceCommand
 

```

NVDisplay.ContainerLocalSystem takes a whooping 16(!) seconds to restart.
NvContainerLocalSystem - doesn't even exist.

Most interesting, even tho I don't have an original issue with the brightness, I can trigger something similar when i boot in eco then set Standard + enable Nvidia GPU only setting in Optimus. Then brightness doesn't work sometimes, and for me restarting `NvContainerLocalSystem` helps, which you don't even have.

**Comment by MaxHornet** [comment]
@seerge ,The nvrestart sometimes takes a while and sometimes its fast don't know why.

I used to have the other services, actually I had 3 of them before : 

1)Nvdia Display Container LS
2)Nvdia LocalSystem Container
3)Nvdia Telemetry Container

I think the other 2 got removed after i did ddu in safe mode and clean installed the driver with nvcleanstall.

That's something interesting to know that mine only works on Display Container restart and your one only on Local system container. 

Few of the people's whose brightness didn't got fixed by the Display Container restart, it might fix on the Local system container restart i guess.

I used to not have this brightness issues maybe before driver 560 versions i guess.

**Comment by seerge** [comment]
@MaxHornet my guess service take long to "restart" cause it's already running (when you boot in Eco mode). 

Since G-Helper does not set it to Disabled / Manual run, it just stops current process when setting Eco which has no effect on reboot.

I can extend this, and actually disable service in Eco, this means device would boot w/o any services running. From other side it's much more "invasive" approach, as if you would suddenly stop using G-Helper or so, services will remain disabled.

**Comment by MaxHornet** [comment]
@seerge yup, your guess is correct. I tried it several times when booting in eco it takes around 16 - 18 seconds max to restart the service. And while in stopped state it starts instantly.

I am not really bothered by the restart time ,as long as it works I am fine with it.

**Comment by seerge** [comment]
@MaxHornet but does just "starting' service help with your brightness issue ? cause when i had a first version of this feature it was disabling nvidia platform + disabling services (and then starting them again ofc), and you mentioned that it didn't seem to fix brightness ?

**Comment by MaxHornet** [comment]
@seerge yes, i tried several times it didn't seem to work that way. But only the second time works. The service has to be started from a stop state for the brightness to work when cold booting in eco. If I remember correctly the nv platform didn't disabled the nv container rather it stopped it. So upon windows restart, nv container was always running.

You can read my long paragraph before there when I tested that for nv platform.

**Comment by MaxHornet** [comment]
> [@MaxHornet](https://github.com/MaxHornet) but does just "starting' service help with your brightness issue ? cause when i had a first version of this feature it was disabling nvidia platform + disabling services (and then starting them again ofc), and you mentioned that it didn't seem to fix brightness ?

@seerge , I gave a thought to this , and just starting the service can work to make it efficient than a restart which takes a while.

There are few things you have to consider for it to work effectively.

1) Disabling the service when switching to eco. So cold booting in eco will always keep the service to stop.

(Also disabling the service keeps nvdia service from not running when booting to eco, so battery benefit still continues after booting instead of stop. )

2)Now instead of Restart just Start the service when switching to standard , but that's not it you have to put it to default automatic one,

*(because if we restart windows in standard mode the service should keep on running for brightness controls to work.)


So implementing this method will require you to configure one additional command, total of 3 i guess:

1) Disable service in eco command.
2) Change service from disable -> automatic command when in standard.
3) Then Start the service command when in standard.


And yes like you have said , services will be disabled if people were to delete ghelper and not use it.  

*(In that case you can put a little warning message which tells the user to set the gpu mode to standard when quitting the app if it's in eco which will enable the services. The popup will only appear in eco mode not standard so it will not be annoying xd:))

Or maybe just put start services command on quit button xd. Just a silly idea :)

**Comment by seerge** [comment]
@MaxHornet sorry for a delayed response,

Disabling service is a bit more invasive (as it won't start automatically w/o G-Helper's involvement anymore), so I'm more keen to see how it works now since it's available as a toggleable feature in UI now.

If other people report that it also fixes their brightness issue - I could dig deeper, and thing on what to do with it :)
