### ISSUE TITLE
HDR - Color Control 2025

### ISSUE THREAD

**Issue by bunyamin59** [seerge/g-helper#4615]
### Rules

- [x] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [x] I understand that, if insufficient information will be provided, my issue will be closed without an answer.

### Is your feature request related to a problem? Please describe

There is a new feature that didnt exist on previous models of scar laptops which is called HDR color control. I think it clamps the color gamut so everything is not overly saturated in hdr. Here is the screenshot from AC.

<img width="992" height="686" alt="Image" src="https://github.com/user-attachments/assets/b26ed9a3-b17f-40c7-965b-b819589cf120" />

### Describe the solution you'd like

Add a toggle for it.

### Device and Model

Strix Scar 16 2025 g635lx

**Comment by seerge** [comment]
@bunyamin59 hello, that's a valid request but I need more info on how does this thing work as I don't own a Strix Scar 2025.

Can you please do the following,

- Quit G-Helper (if you had it running)
- Open `%appdata%\GHelper\config.json`
- Add following line to the top of the config and save it
```
"debug":1,
```

1. After that run G-Helper, open `Extra` and click on a new `Zoom Glass` icon to run endpoint scan.
2. Change HDR Color Control toggle in AC to the opposite, and run scan in G-Helper again

Upload generated `scan.txt` here :)

Thanks in advance.

**Comment by bunyamin59** [comment]
[scan.txt](https://github.com/user-attachments/files/22704188/scan.txt) Okay here it is. If its doable i think it would look good in place of the multi zone toggle when hdr is enabled.

**Comment by seerge** [comment]
@bunyamin59 ok, thanks!

Is it visually noticeable when you toggle this new setting ?

I see a new endpoint changing value : ``50071``

If so, try to do the following
- Open G-Helper's `Extra` settings
- Set `50071` as first field in ACPI DEVS test and 0 / 1 as second, and click `Send`

Does screen visually change ?

**Comment by bunyamin59** [comment]
yes. 0 is the vivid color mode and 1 is true color mode.

**Comment by seerge** [comment]
@bunyamin59 ok, sorry for a delay. Try this build

I have tried to do like you asked.

- When HDR is ON and `50071` flag exists it will show `HDR Color Control` button and hide `Multizone` button (to keep screen buttons in one row)
- When HDR is OFF - it will hide `HDR Color Control`

[GHelper.zip](https://github.com/user-attachments/files/22910812/GHelper.zip)

**Comment by bunyamin59** [comment]
thank you. when the button is not highlighted it doesnt click/work again. i got it to work once when it was highlighted. it also doesnt go away when the hdr is turned off. i needed to reopen the app to get zone control. keybinds work tho.

**Comment by seerge** [comment]
@bunyamin59 

1. App checks for HDR status only every time you open main window (not in realtime to save resources). So opening window again (not restarting) should be enough. 

2. Can you post a log from `%appdata%\GHelper` after trying to toggle it on / off?

**Comment by bunyamin59** [comment]
[log.txt](https://github.com/user-attachments/files/22930475/log.txt) here is the log file. closing and reopening the window doesnt work either. zone control only comes up if i restart the app.

**Comment by seerge** [comment]
@bunyamin59 ok, can you try this build and upload log from it agian

It should dynamically show / hide button when HDR is enabled / disabled.

As for actual toggle, I'm a bit confused. Currently app just reads `50071` value and then sets the opposite when button is clicked. So it should be working in original build too. I have added a short delay before "re-reading" the status and therefore highlighting a button.

Does actual screen change when you click it ?

[GHelper.zip](https://github.com/user-attachments/files/22930737/GHelper.zip)

**Comment by bunyamin59** [comment]
it worked once when the button was red initially. but after toggling once it never worked and button didnt change states. even if i set it to 0/1 manually the button changes states but doesnt work. with this build the issue remains. also when hdr is turned off the multizone button also goes missing now and the space remains empty.

**Comment by seerge** [comment]
@bunyamin59 hmm, may be flag reporting is swapped by some reason in firmware ?

Does the scan show 1 when HDR Control is Enabled and 0 when it's disabled ?
Does setting DEVS 0x0050071 to 1 sets it Enabled, and 0 sets it disabled ?

Try this build with swapped status

[GHelper.zip](https://github.com/user-attachments/files/22931043/GHelper.zip)

**Comment by bunyamin59** [comment]
this build works perfectly other than a momentary flicker when color control is changed. if you plan to add this going forward i think you can rename the off state in this build to true color and the on state to vivid or somehting along those lines. i think asus also named it that way in the app.

**Comment by bunyamin59** [comment]
by flicker i mean the app window flickers.

**Comment by seerge** [comment]
@bunyamin59 can you check if window still flickers in this build ? 

[GHelper.zip](https://github.com/user-attachments/files/22931253/GHelper.zip)

**Comment by bunyamin59** [comment]
no it is fixed with this build. thank you for your efforts.

**Comment by seerge** [comment]
@bunyamin59 ok, great. Then I assume it works as it should ? Closing as resolved.

Thanks for the discovery!

**Comment by bunyamin59** [comment]
i also realized that with the last two builds that are actually working after toggling off the color mode or toggling off the multizone so the buttons are not highlighted the button still remains selected. i can select other elements by tab and clicking off the window removes it but after window is in focus the button gets selected again.

**Comment by seerge** [comment]
@bunyamin59 does it apply for Multizone as well ? cause that's something new

As for HDR Control - is it also inverted (i.e. highlighted when OFF and not highlighted when ON ) ?

**Comment by bunyamin59** [comment]
what i meant was this

<img width="486" height="91" alt="Image" src="https://github.com/user-attachments/assets/969458a2-700c-4a3f-8e42-f284cc115b83" /> idk if this is normal behaviour.
i mean if we think of the vivid as on and true color as off yeah it is working as intented. the button highlights when the display is in vivid mode. but as you can see in my original screenshot the button is highlighted when true color mode is selected i think. i have since removed AC and need to reinstall to check for sure.

**Comment by bunyamin59** [comment]
also would it be possible to assign a keybind to this function?

**Comment by seerge** [comment]
@bunyamin59 on your screenshot it says that mini-led status is One-Zone (i.e. OFF), there is no border there. It's just a default windows focus over button :) if you will click `Tab` focus will jump to next button.

Or I simply don't understand what you mean still :)

**Comment by bunyamin59** [comment]
yeah thats what i meant. ive never seen that without intentionally pressing tab so wondered if it should be like that. Also sometimes the button stops working but when that happens manually setting 0/1 also stops working so i assume it is a problem with my system or asus.

**Comment by seerge** [comment]
@bunyamin59 well, you can double check with DEVS command under extra, if that also stops working - it could be some strange firmware hiccup :|
